region              = "us-east-1"
instance_type       = "t2.micro"
key_name            = "devops-key"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
ecr_repo_name       = "nginx-repo"
